webtalk_init -webtalk_dir D:\\xilinx\\project\\spartan_cam\\spartan_cam.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-05-31 13:49:22" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "42vqfluoksqat98954oj43nbe8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.079 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1559280328315" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key Arch -value "spartan7" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key Device -value "7s15" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1559280328315"
webtalk_add_data -client sdk -key uid -value "1559280351073" -context "sdk\\\\bsp/1559280351073"
webtalk_add_data -client sdk -key hwid -value "1559280328315" -context "sdk\\\\bsp/1559280351073"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1559280351073"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1559280351073"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1559280351073"
webtalk_add_data -client sdk -key uid -value "1559280352399" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key hwid -value "1559280328315" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key bspid -value "1559280351073" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key projSize -value "7.83984375" -context "sdk\\\\application/1559280352399"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1559281762811"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1559281762811"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1559281762811"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1559281762811"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1559281762811"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1559281762811"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1559281762811"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1559281762811"
webtalk_transmit -clientid 1648237688 -regid "" -xml D:\\xilinx\\project\\spartan_cam\\spartan_cam.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\xilinx\\project\\spartan_cam\\spartan_cam.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\xilinx\\project\\spartan_cam\\spartan_cam.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
