# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lesag/Documents/University/Personal_Projects/camera-filters/vivado/spartan_cam.srcs/sources_1/bd/system/ip/system_csi2_d_phy_rx_0_1/system_csi2_d_phy_rx_0_1.xci
# IP: The module: 'system_csi2_d_phy_rx_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lesag/Documents/University/Personal_Projects/camera-filters/vivado/spartan_cam.srcs/sources_1/bd/system/ip/system_csi2_d_phy_rx_0_1/hdl/csi2_d_phy_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_csi2_d_phy_rx_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/lesag/Documents/University/Personal_Projects/camera-filters/vivado/spartan_cam.srcs/sources_1/bd/system/ip/system_csi2_d_phy_rx_0_1/system_csi2_d_phy_rx_0_1.xci
# IP: The module: 'system_csi2_d_phy_rx_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lesag/Documents/University/Personal_Projects/camera-filters/vivado/spartan_cam.srcs/sources_1/bd/system/ip/system_csi2_d_phy_rx_0_1/hdl/csi2_d_phy_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_csi2_d_phy_rx_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
